project_id: "stunning-ruler-473613-b9"
organization_id: "123456789012"
billing_account: "01949F-69D66D-E7B8F6"
credentials_file: "keys.json"  
labels:
  owner: "intern"
  environment: "test"
apis:
  - compute.googleapis.com
  - iam.googleapis.com
